### ISSUE TITLE
开启中英混输后，无法在双拼中输入 ;  

### ISSUE THREAD

**Issue by Mr-Zhen** [BlindingDark/rime-easy-en#22]
我使用的微软双拼方案中; 代表 ing ，开启中英混输后输入; 会导致当前内容上屏。

**Comment by BlindingDark** [comment]
已修复

你可以使用 plum 进行更新：

```sh
bash rime-install BlindingDark/rime-easy-en:customize:schema=double_pinyin_mspy 
```

也可以下载最新版本的文件，然后手动修改 `double_pinyin_mspy.custom.yaml`，增加 `__include: easy_en:/patch_double_pinyin_mspy`，即效果如下：

```yaml
# Rx: BlindingDark/rime-easy-en:customize:schema=double_pinyin_mspy {
  - patch/+:
      __include: easy_en:/patch
      __include: easy_en:/patch_double_pinyin_mspy
# }

```
