### ISSUE TITLE
请问如何关闭显示无意义的英文字符串?

### ISSUE THREAD

**Issue by nigolarer** [BlindingDark/rime-easy-en#27]
我按照教程安装了easy-en实现了明月拼音的中英文混输, 这很棒. 但是有一个问题就是这里的英文会返回一些拼音或者毫无意义的单词, 比如我输入: `zhy` 预期返回: `这样`, 但是首个返回词是: `ZHY`, 同样地, 还有: `zhge` 的首选词是: `ZHGE`, 这些符号对我毫无意义, 我只想实现中文输入的时候能够进行单词拼写的确认. 不是英文的字符我不想返回, 请问应该如何设置?

**Comment by BlindingDark** [comment]
你好，根据 readme 中的说明配置是否能解决问题呢？

https://github.com/BlindingDark/rime-easy-en#%E6%B7%B7%E8%BE%93%E6%97%B6%E5%87%BA%E7%8E%B0%E5%B8%A6%E6%9C%89%E5%9B%BE%E6%A1%88%E7%9A%84%E8%8B%B1%E6%96%87

**Comment by nigolarer** [comment]
> 你好，根据 readme 中的说明配置是否能解决问题呢？
> 
> https://github.com/BlindingDark/rime-easy-en#%E6%B7%B7%E8%BE%93%E6%97%B6%E5%87%BA%E7%8E%B0%E5%B8%A6%E6%9C%89%E5%9B%BE%E6%A1%88%E7%9A%84%E8%8B%B1%E6%96%87

非常感谢.  我本地没有custom这个yml文件, 新建之后按照说明填入了如下信息并重新部署后似乎还是没用:
```
# encoding: utf-8
patch:
  translator/enable_sentence: false
```

幸运的是, 我在`easy_en.yaml`中看到了`enable_sentence: true` 这个选项, 将它改为`false`并重新部署后问题解决了:
```
# easy_en.yamlL15
patch:
  schema/dependencies/@next: easy_en
  engine/translators/@next: table_translator@easy_en
  easy_en:
    __include: easy_en.schema:/translator
    enable_completion: true
    enable_sentence: false  # 这里设置为false即可
    initial_quality: -1
  recognizer/patterns/uppercase: ''
  speller/alphabet:
    __include: easy_en.schema:/speller/alphabet
```

真没想到"这个"一词原来我一直输入的是"zhge", 一直是靠输入法纠错 :P
