### ISSUE TITLE
手动安装，微软双拼无法开启中英混输

### ISSUE THREAD

**Issue by burg1ar** [BlindingDark/rime-easy-en#30]
操作系统：ubuntu 18.04
输入法：fcitx-rime，double_pinyin_mspy
部署方式：参照“手动安装easy_en”
结果：无法开启中英混输

**Comment by burg1ar** [comment]
具体的操作步骤：
1. 将 ` easy_en.dict.yaml` `easy_en.yaml` `lua/easy_en.lua` 复制到 rime 配置目录。
2. 在 `double_pinyin_mspy.custom.yaml` 中添加：
    ```
        patch:
        __include: easy_en:/patch_double_pinyin_mspy
    ```
3. 重新部署
结果，中英混输没有生效
我是否遗漏了什么步骤

**Comment by BlindingDark** [comment]
能否将完整的配置分享一下？

**Comment by burg1ar** [comment]
default.custom.yaml:
```yaml
patch:
  schema_list:
    - schema: double_pinyin_mspy
    - schema: luna_pinyin_simp
```

default.yaml:
```yaml
ascii_composer:
  good_old_caps_lock: true
  switch_key:
    Caps_Lock: clear
    Control_L: noop
    Control_R: noop
    Eisu_toggle: clear
    Shift_L: inline_ascii
    Shift_R: commit_text
config_version: 0.35.custom.930421487
customization: 930421487
key_binder:
  bindings:
    - {accept: "Control+p", send: Up, when: composing}
    - {accept: "Control+n", send: Down, when: composing}
    - {accept: "Control+b", send: Left, when: composing}
    - {accept: "Control+f", send: Right, when: composing}
    - {accept: "Control+a", send: Home, when: composing}
    - {accept: "Control+e", send: End, when: composing}
    - {accept: "Control+d", send: Delete, when: composing}
    - {accept: "Control+k", send: "Shift+Delete", when: composing}
    - {accept: "Control+h", send: BackSpace, when: composing}
    - {accept: "Control+g", send: Escape, when: composing}
    - {accept: "Control+bracketleft", send: Escape, when: composing}
    - {accept: "Alt+v", send: Page_Up, when: composing}
    - {accept: "Control+v", send: Page_Down, when: composing}
    - {accept: ISO_Left_Tab, send: Page_Up, when: composing}
    - {accept: "Shift+Tab", send: Page_Up, when: composing}
    - {accept: Tab, send: Page_Down, when: composing}
    - {accept: minus, send: Page_Up, when: has_menu}
    - {accept: equal, send: Page_Down, when: has_menu}
    - {accept: comma, send: Page_Up, when: paging}
    - {accept: period, send: Page_Down, when: has_menu}
    - {accept: "Control+Shift+1", select: .next, when: always}
    - {accept: "Control+Shift+2", toggle: ascii_mode, when: always}
    - {accept: "Control+Shift+3", toggle: full_shape, when: always}
    - {accept: "Control+Shift+4", toggle: simplification, when: always}
    - {accept: "Control+Shift+5", toggle: extended_charset, when: always}
    - {accept: "Control+Shift+exclam", select: .next, when: always}
    - {accept: "Control+Shift+at", toggle: ascii_mode, when: always}
    - {accept: "Control+Shift+numbersign", toggle: full_shape, when: always}
    - {accept: "Control+Shift+dollar", toggle: simplification, when: always}
    - {accept: "Control+Shift+percent", toggle: extended_charset, when: always}
    - {accept: "Shift+space", toggle: full_shape, when: always}
    - {accept: "Control+period", toggle: ascii_punct, when: always}
menu:
  page_size: 5
punctuator:
  full_shape:
    " ": {commit: "　"}
    "!": {commit: "！"}
    "\"": {pair: ["“", "”"]}
    "#": ["＃", "⌘"]
    "$": ["￥", "$", "€", "£", "¥", "¢", "¤"]
    "%": ["％", "°", "℃"]
    "&": "＆"
    "'": {pair: ["‘", "’"]}
    "(": "（"
    ")": "）"
    "*": ["＊", "·", "・", "×", "※", "❂"]
    "+": "＋"
    ",": {commit: "，"}
    "-": "－"
    .: {commit: "。"}
    "/": ["／", "÷"]
    ":": {commit: "："}
    ";": {commit: "；"}
    "<": ["《", "〈", "«", "‹"]
    "=": "＝"
    ">": ["》", "〉", "»", "›"]
    "?": {commit: "？"}
    "@": ["＠", "☯"]
    "[": ["「", "【", "〔", "［"]
    "\\": ["、", "＼"]
    "]": ["」", "】", "〕", "］"]
    "^": {commit: "……"}
    _: "——"
    "`": "｀"
    "{": ["『", "〖", "｛"]
    "|": ["·", "｜", "§", "¦"]
    "}": ["』", "〗", "｝"]
    "~": "～"
  half_shape:
    "!": {commit: "！"}
    "\"": {pair: ["“", "”"]}
    "#": "#"
    "$": ["￥", "$", "€", "£", "¥", "¢", "¤"]
    "%": ["%", "％", "°", "℃"]
    "&": "&"
    "'": {pair: ["‘", "’"]}
    "(": "（"
    ")": "）"
    "*": ["*", "＊", "·", "・", "×", "※", "❂"]
    "+": "+"
    ",": {commit: "，"}
    "-": "-"
    .: {commit: "。"}
    "/": ["、", "/", "／", "÷"]
    ":": {commit: "："}
    ";": {commit: "；"}
    "<": ["《", "〈", "«", "‹"]
    "=": "="
    ">": ["》", "〉", "»", "›"]
    "?": {commit: "？"}
    "@": "@"
    "[": ["「", "【", "〔", "［"]
    "\\": ["、", "\\", "＼"]
    "]": ["」", "】", "〕", "］"]
    "^": {commit: "……"}
    _: "——"
    "`": "`"
    "{": ["『", "〖", "｛"]
    "|": ["·", "|", "｜", "§", "¦"]
    "}": ["』", "〗", "｝"]
    "~": ["~", "～"]
recognizer:
  patterns:
    email: "^[A-Za-z][-_.0-9A-Za-z]*@.*$"
    uppercase: "[A-Z][-_+.'0-9A-Za-z]*$"
    url: "^(www[.]|https?:|ftp[.:]|mailto:|file:).*$|^[a-z]+[.].+$"
schema_list:
  - schema: double_pinyin_mspy
  - schema: luna_pinyin_simp
switcher:
  abbreviate_options: true
  caption: "〔方案選單〕"
  fold_options: true
  hotkeys:
    - "Control+grave"
    - "Control+Shift+grave"
    - F4
  option_list_separator: "／"
  save_options:
    - full_shape
    - ascii_punct
    - simplification
    - extended_charset
```

double_pinyin_mspy.custom.yaml:
```yaml
patch:
  translator/dictionary: luna_pinyin.extended
  __include: easy_en:/patch_double_pinyin_mspy
  engine/translators:
    - punct_translator
    - reverse_lookup_translator
    - script_translator
    - table_translator@custom_phrase
    - table_translator
  custom_phrase:
    dictionary: ""
    user_dict: custom_phrase
    db_class: stabledb
    enable_completion: false
    enable_sentence: false
    initial_quality: 1
```

double_pinyin_mspy.schema.yaml:
```yaml
__include: "easy_en:/patch_double_pinyin_mspy"
custom_phrase:
  db_class: stabledb
  dictionary: ""
  enable_completion: false
  enable_sentence: false
  initial_quality: 1
  user_dict: custom_phrase
customization: 549439220
engine:
  filters:
    - simplifier
    - uniquifier
  processors:
    - ascii_composer
    - recognizer
    - key_binder
    - speller
    - punctuator
    - selector
    - navigator
    - express_editor
  segmentors:
    - ascii_segmentor
    - matcher
    - abc_segmentor
    - punct_segmentor
    - fallback_segmentor
  translators:
    - punct_translator
    - reverse_lookup_translator
    - script_translator
    - "table_translator@custom_phrase"
    - table_translator
key_binder:
  import_preset: default
punctuator:
  import_preset: default
recognizer:
  import_preset: default
  patterns:
    reverse_lookup: "`[a-z]*'?$"
reverse_lookup:
  comment_format:
    - "xform/([nl])v/$1ü/"
  dictionary: stroke
  enable_completion: true
  preedit_format:
    - "xlit/hspnz/一丨丿丶乙/"
  prefix: "`"
  suffix: "'"
  tips: "〔筆畫〕"
schema:
  author:
    - "佛振 <chen.sst@gmail.com>"
  dependencies:
    - stroke
  description: |
    朙月拼音＋MSPY雙拼方案。
    
  name: "MSPY雙拼"
  schema_id: double_pinyin_mspy
  version: 0.15.custom.549439220
speller:
  algebra:
    - "erase/^xx$/"
    - "derive/^([jqxy])u$/$1v/"
    - "derive/^([aoe].*)$/o$1/"
    - "xform/^([ae])(.*)$/$1$1$2/"
    - "xform/iu$/Q/"
    - "xform/[iu]a$/W/"
    - "xform/er$|[uv]an$/R/"
    - "xform/[uv]e$/T/"
    - "xform/v$|uai$/Y/"
    - "xform/^sh/U/"
    - "xform/^ch/I/"
    - "xform/^zh/V/"
    - "xform/uo$/O/"
    - "xform/[uv]n$/P/"
    - "xform/i?ong$/S/"
    - "xform/[iu]ang$/D/"
    - "xform/(.)en$/$1F/"
    - "xform/(.)eng$/$1G/"
    - "xform/(.)ang$/$1H/"
    - "xform/ian$/M/"
    - "xform/(.)an$/$1J/"
    - "xform/iao$/C/"
    - "xform/(.)ao$/$1K/"
    - "xform/(.)ai$/$1L/"
    - "xform/(.)ei$/$1Z/"
    - "xform/ie$/X/"
    - "xform/ui$/V/"
    - "derive/T$/V/"
    - "xform/(.)ou$/$1B/"
    - "xform/in$/N/"
    - "xform/ing$/;/"
    - "xlit/QWRTYUIOPSDFGHMJCKLZXVBN/qwrtyuiopsdfghmjcklzxvbn/"
  alphabet: "zyxwvutsrqponmlkjihgfedcba;"
  delimiter: " '"
  initials: zyxwvutsrqponmlkjihgfedcba
switches:
  - name: ascii_mode
    reset: 0
    states: ["中文", "西文"]
  - name: full_shape
    states: ["半角", "全角"]
  - name: simplification
    states: ["漢字", "汉字"]
  - name: ascii_punct
    states: ["。，", "．，"]
translator:
  dictionary: luna_pinyin.extended
  preedit_format:
    - "xform/([aoe])(\\w)/0$2/"
    - "xform/([bpmnljqxy])n/$1in/"
    - "xform/(\\w)g/$1eng/"
    - "xform/(\\w)q/$1iu/"
    - "xform/([gkhvuirzcs])w/$1ua/"
    - "xform/(\\w)w/$1ia/"
    - "xform/([dtnlgkhjqxyvuirzcs])r/$1uan/"
    - "xform/0r/er/"
    - "xform/([dtgkhvuirzcs])v/$1ui/"
    - "xform/(\\w)v/$1ve/"
    - "xform/(\\w)t/$1ve/"
    - "xform/([gkhvuirzcs])y/$1uai/"
    - "xform/(\\w)y/$1v/"
    - "xform/([dtnlgkhvuirzcs])o/$1uo/"
    - "xform/(\\w)p/$1un/"
    - "xform/([jqx])s/$1iong/"
    - "xform/(\\w)s/$1ong/"
    - "xform/([jqxnl])d/$1iang/"
    - "xform/(\\w)d/$1uang/"
    - "xform/(\\w)f/$1en/"
    - "xform/(\\w)h/$1ang/"
    - "xform/(\\w)j/$1an/"
    - "xform/(\\w)k/$1ao/"
    - "xform/(\\w)l/$1ai/"
    - "xform/(\\w)z/$1ei/"
    - "xform/(\\w)x/$1ie/"
    - "xform/(\\w)c/$1iao/"
    - "xform/(\\w)b/$1ou/"
    - "xform/(\\w)m/$1ian/"
    - "xform/(\\w);/$1ing/"
    - "xform/0(\\w)/$1/"
    - "xform/(^|[ '])v/$1zh/"
    - "xform/(^|[ '])i/$1ch/"
    - "xform/(^|[ '])u/$1sh/"
    - "xform/([jqxy])v/$1u/"
    - "xform/([nl])v/$1ü/"
  prism: double_pinyin_mspy
```

词库和短语什么的我就不分享了
如果还需要什么其他信息，请告知，感谢

**Comment by burg1ar** [comment]
另外，rime目录结构如下：
```
rime
├── cangjie5_express.prism.bin -> /usr/share/rime-data/cangjie5_express.prism.bin
├── cangjie5.prism.bin -> /usr/share/rime-data/cangjie5.prism.bin
├── cangjie5.reverse.bin -> /usr/share/rime-data/cangjie5.reverse.bin
├── cangjie5.schema.yaml
├── cangjie5.table.bin -> /usr/share/rime-data/cangjie5.table.bin
├── custom_phrase.txt
├── default.custom.yaml
├── default.yaml
├── double_pinyin_abc.prism.bin -> /usr/share/rime-data/double_pinyin_abc.prism.bin
├── double_pinyin_flypy.prism.bin -> /usr/share/rime-data/double_pinyin_flypy.prism.bin
├── double_pinyin_mspy.custom.yaml
├── double_pinyin_mspy.prism.bin
├── double_pinyin_mspy.schema.yaml
├── double_pinyin.prism.bin -> /usr/share/rime-data/double_pinyin.prism.bin
├── easy_en.dict.yaml
├── easy_en.schema.yaml
├── easy_en.yaml
├── installation.yaml
├── lua
│   └── easy_en.lua
├── luna_pinyin.extended.dict.yaml
├── luna_pinyin.extended.reverse.bin
├── luna_pinyin.extended.table.bin
├── luna_pinyin_fluency.prism.bin -> /usr/share/rime-data/luna_pinyin_fluency.prism.bin
├── luna_pinyin_fluency.schema.yaml
├── luna_pinyin.prism.bin
├── luna_pinyin.reverse.bin -> /usr/share/rime-data/luna_pinyin.reverse.bin
├── luna_pinyin.schema.yaml
├── luna_pinyin_simp.custom.yaml
├── luna_pinyin_simp.prism.bin
├── luna_pinyin_simp.schema.yaml
├── luna_pinyin.table.bin -> /usr/share/rime-data/luna_pinyin.table.bin
├── luna_pinyin_tw.prism.bin -> /usr/share/rime-data/luna_pinyin_tw.prism.bin
├── luna_pinyin_tw.schema.yaml
├── luna_pinyin.userdb
│   ├── 000198.ldb
│   ├── 000200.ldb
│   ├── 000207.ldb
│   ├── 000210.log
│   ├── CURRENT
│   ├── LOCK
│   ├── LOG
│   ├── LOG.old
│   └── MANIFEST-000209
├── luna_pinyin.zhwiki.dict.yaml
├── symbols.yaml
├── sync
│   └── 2775cec6-4d6a-44a6-8d64-1142131dd23d
│       ├── cangjie5.schema.yaml
│       ├── custom_phrase.txt
│       ├── default.custom.yaml
│       ├── default.yaml
│       ├── double_pinyin_mspy.custom.yaml
│       ├── double_pinyin_mspy.schema.yaml
│       ├── easy_en.dict.yaml
│       ├── easy_en.schema.yaml
│       ├── easy_en.yaml
│       ├── installation.yaml
│       ├── luna_pinyin.extended.dict.yaml
│       ├── luna_pinyin_fluency.schema.yaml
│       ├── luna_pinyin.schema.yaml
│       ├── luna_pinyin_simp.schema.yaml
│       ├── luna_pinyin_tw.schema.yaml
│       ├── luna_pinyin.userdb.txt
│       ├── luna_pinyin.zhwiki.dict.yaml
│       ├── symbols.yaml
│       └── user.yaml
└── user.yaml
```

**Comment by BlindingDark** [comment]
好的 有空我在我电脑上帮你看看 😎

**Comment by BlindingDark** [comment]
@burg1ar 经过排查，你可以尝试以下放方法

1. 关闭连续输入增强 [点我](https://github.com/BlindingDark/rime-easy-en#%E4%B8%8D%E4%BD%BF%E7%94%A8%E8%BF%9E%E7%BB%AD%E8%BE%93%E5%85%A5%E5%A2%9E%E5%BC%BA)

2. 提高单词排序权重 [点我](https://github.com/BlindingDark/rime-easy-en#%E4%B8%8D%E4%BD%BF%E7%94%A8%E8%BF%9E%E7%BB%AD%E8%BE%93%E5%85%A5%E5%A2%9E%E5%BC%BA)

**Comment by burg1ar** [comment]
尝试：
1. 创建文件：`easy_en.custom.yaml`，并添加内容：
  ```yaml
  patch:
  engine/filters:
    - uniquifier
  ```
2. `double_pinyin_mspy.custom.yaml`开头修改为：
  ```yaml
  patch:
    translator/dictionary: luna_pinyin.extended
    # the following two lines are for esay_en
    __include: easy_en:/patch_double_pinyin_mspy
    easy_en/initial_quality: 0.5
  ```
测试：
在双拼模式，输入“hello”得到显示：
![image](https://user-images.githubusercontent.com/3461895/144783703-5abd8680-0da3-4a08-83b7-f47fa9c8a485.png)
问题似乎没有得到修复
