### ISSUE TITLE
手动配置混输模式，与挂载词库产生冲突

### ISSUE THREAD

**Issue by quitdoing** [BlindingDark/rime-easy-en#36]
操作过程：
1、将 easy_en.schema.yaml easy_en.dict.yaml easy_en.yaml lua/easy_en.lua 复制到 rime 配置目录。
2、在 luna_pinyin.custom.yaml 文件中的 patch 下添加 __include: easy_en:/patch。
3、重新布署rime。
结果发现rime只能输入英文，无法输入中文，注释掉 __include: easy_en:/patch后可正常输入中文。注释掉luna_pinyin.custom.yaml 文件中的translator/dictionary: luna_pinyin.extended后可以正常中英混输。

**Comment by BlindingDark** [comment]
能否尝试将 `__include: easy_en:/patch` 放在 `translator/dictionary: luna_pinyin.extended` 的后面？

**Comment by Yukai-Qian** [comment]
@quitdoing 我找到了一个解决方法，供你参考：

1. 不要添加 `__include: easy_en:/patch` 一行
2. 在 `luna_pinyin.custom.yaml` 中，添加如下几行：
```yaml
patch:
  "engine/translators/+":
    - table_translator@easy_en
  "schema/dependencies/+":
    - easy_en
  easy_en:
    __include: easy_en.schema:/translator
    enable_completion: true
    enable_sentence: true
    initial_quality: -1
  "recognizer/patterns/uppercase": ''
  "speller/alphabet":
    __include: easy_en.schema:/speller/alphabet
```

@BlindingDark 看起来这几行的作用和只添加一行 `__include: easy_en:/patch` 的作用理应是一样的，但确实只有手动添加这几行才能正常工作。希望对你 debug 有帮助！
